version: "1.0"

services:
  hacga1:
    build: .
    container_name: hacga1
    privileged: true
    volumes:
      - ${PWD}/test_data:/data
      - ${HOME}/.gm_key:/root/.gm_key:ro
    environment:
      - HOME=/root
    stdin_open: true
    tty: true

